export const REQUEST_CATALOG = 'REQUEST_CATALOG';
export const RECEIVE_CATALOG = 'RECEIVE_CATALOG';
export const REQUEST_CATALOG_FAILED = 'REQUEST_CATALOG_FAILED';

export const REQUEST_SOURCE_METADATA = 'REQUEST_SOURCE_METADATA';
export const RECEIVE_SOURCE_METADATA = 'RECEIVE_SOURCE_METADATA';
export const REQUEST_SOURCE_METADATA_FAILED = 'REQUEST_SOURCE_METADATA_FAILED';
