export const REQUEST_CATALOG = 'REQUEST_CATALOG';
export const RECEIVE_CATALOG = 'RECEIVE_CATALOG';
export const REQUEST_CATALOG_FAILED = 'REQUEST_CATALOG_FAILED';

export const REQUEST_SOURCE_METADATA = 'REQUEST_SOURCE_METADATA';
export const RECEIVE_SOURCE_METADATA = 'RECEIVE_SOURCE_METADATA';
export const REQUEST_SOURCE_METADATA_FAILED = 'REQUEST_SOURCE_METADATA_FAILED';

export const REQUEST_SOURCE_METADATA_DELETE = 'REQUEST_SOURCE_METADATA_DELETE';
export const REQUEST_SOURCE_METADATA_DELETE_FAILED = 'REQUEST_SOURCE_METADATA_DELETE_FAILED';
export const REQUEST_SOURCE_METADATA_DELETED = 'REQUEST_SOURCE_METADATA_DELETED';

export const REQUEST_SOURCE_THUMBS = 'REQUEST_SOURCE_THUMBS';
export const RECEIVE_SOURCE_THUMBS = 'RECEIVE_SOURCE_THUMBS';
export const REQUEST_SOURCE_THUMBS_FAILED = 'REQUEST_SOURCE_THUMBS_FAILED';

export const GENERATE_SOURCE_THUMB = 'GENERATE_SOURCE_THUMB';
export const SOURCE_THUMB_GENERATED = 'SOURCE_THUMB_GENERATED';
export const GENERATE_SOURCE_THUMB_FAILED = 'GENERATE_SOURCE_THUMB_FAILED';
